2023-03-20 13:37:00,044 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 13:37:00,044 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:37:00,044 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:37:00,147 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:37:00,147 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:37:00,147 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:37:00,147 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:37:00,177 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:37:00,177 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:37:00,178 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:37:00,178 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:37:00,207 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:37:00,207 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:37:00,207 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:37:00,207 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:37:00,237 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:37:00,237 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:37:00,237 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 13:37:00,237 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:37:03,251 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:37:06,253 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:37:09,266 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:37:12,278 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:37:15,280 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:37:18,293 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:37:21,294 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:37:24,309 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:09,566 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 13:45:09,566 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 13:45:09,566 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:45:09,566 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:45:09,636 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:45:09,636 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:45:09,636 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 13:45:09,636 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:12,649 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:15,669 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:18,672 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:21,686 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:24,698 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:27,712 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:30,726 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:33,741 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:45:36,753 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:47:14,595 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 13:47:14,596 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 13:47:14,596 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:47:14,596 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:47:14,662 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:47:14,662 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:47:14,662 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 13:47:14,662 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:47:17,675 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:47:20,720 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:16,956 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 13:48:16,956 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 13:48:16,956 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:48:16,956 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:48:17,053 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:48:17,054 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:48:17,054 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 13:48:17,055 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:20,068 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:23,152 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:26,261 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:29,275 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:32,288 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:35,299 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:38,316 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:41,323 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:44,339 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:47,350 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:50,366 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:48:53,383 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:50:04,777 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 13:50:04,777 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 13:50:04,777 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:50:04,778 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:50:04,909 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:50:04,913 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:50:04,913 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 13:50:04,913 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:50:07,925 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:52:45,590 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 13:52:45,590 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 13:52:45,590 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:52:45,592 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:52:45,687 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:52:45,688 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:52:45,690 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 13:52:45,691 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:52:48,703 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 13:53:55,966 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 13:53:55,966 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 13:53:55,968 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 13:53:55,970 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 13:53:56,057 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 13:53:56,058 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 13:53:56,058 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 13:53:56,059 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 17:50:28,124 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 17:50:28,125 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 17:50:28,126 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 17:50:28,132 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 17:50:28,434 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 17:50:28,436 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 17:50:28,436 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 17:50:28,436 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 17:50:31,451 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 17:51:22,559 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 17:51:22,560 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 17:51:22,560 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 17:51:22,562 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 17:51:22,669 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 17:51:22,670 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 17:51:22,670 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 17:51:22,671 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 17:51:25,686 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 17:56:51,671 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 17:56:51,673 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 17:56:51,675 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 17:56:51,677 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 17:56:51,814 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 17:56:51,817 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 17:56:51,818 [INFO ] [OPC-DA] Inicialização completa, executando processo de conversação OPC DA.
2023-03-20 17:56:51,818 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 17:56:54,821 [DEBUG] [OPC-DA] Nova leitura.
2023-03-20 18:01:08,095 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:01:08,103 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:01:08,109 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:01:08,114 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:01:08,415 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:01:08,419 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:01:08,420 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "TypeError("read(): 'tags' parameter must be a string or a list of strings",)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE, group=0)
  File "C:\Users\cog\AppData\Local\Programs\Python\Python36-32\lib\site-packages\OpenOPC.py", line 610, in read
    raise TypeError("read(): 'tags' parameter must be a string or a list of strings")
TypeError: read(): 'tags' parameter must be a string or a list of strings
2023-03-20 18:01:08,427 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x02841DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE, group=0)
  File "C:\Users\cog\AppData\Local\Programs\Python\Python36-32\lib\site-packages\OpenOPC.py", line 610, in read
    raise TypeError("read(): 'tags' parameter must be a string or a list of strings")
TypeError: read(): 'tags' parameter must be a string or a list of strings
2023-03-20 18:01:10,441 [DEBUG] [OPC-DA] Tentativa -> 2/3
2023-03-20 18:01:10,444 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:01:10,446 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:01:10,487 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:01:10,488 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:01:10,489 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "TypeError("read(): 'tags' parameter must be a string or a list of strings",)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE, group=0)
  File "C:\Users\cog\AppData\Local\Programs\Python\Python36-32\lib\site-packages\OpenOPC.py", line 610, in read
    raise TypeError("read(): 'tags' parameter must be a string or a list of strings")
TypeError: read(): 'tags' parameter must be a string or a list of strings
2023-03-20 18:01:10,491 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x02841DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE, group=0)
  File "C:\Users\cog\AppData\Local\Programs\Python\Python36-32\lib\site-packages\OpenOPC.py", line 610, in read
    raise TypeError("read(): 'tags' parameter must be a string or a list of strings")
TypeError: read(): 'tags' parameter must be a string or a list of strings
2023-03-20 18:01:34,689 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:01:34,690 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:01:34,691 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:01:34,693 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:01:34,805 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:01:34,806 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:01:34,827 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "TypeError("'tuple' object does not support item assignment",)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(k, group=0)
TypeError: 'tuple' object does not support item assignment
2023-03-20 18:01:34,830 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x02451DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(k, group=0)
TypeError: 'tuple' object does not support item assignment
2023-03-20 18:01:36,840 [DEBUG] [OPC-DA] Tentativa -> 2/3
2023-03-20 18:01:36,842 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:01:36,844 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:01:36,885 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:01:36,888 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:02:26,050 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:02:26,050 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:02:26,051 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:02:26,052 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:02:26,151 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:02:26,151 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:02:26,164 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "TypeError("'str' object does not support item assignment",)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(k, group=0)
TypeError: 'str' object does not support item assignment
2023-03-20 18:02:26,168 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x024B1DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(k, group=0)
TypeError: 'str' object does not support item assignment
2023-03-20 18:02:53,734 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:02:53,734 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:02:53,735 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:02:53,736 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:02:53,818 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:02:53,820 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:02:53,832 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "TypeError("'str' object does not support item assignment",)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[k], group=0)
TypeError: 'str' object does not support item assignment
2023-03-20 18:02:53,836 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x01C51DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[k], group=0)
TypeError: 'str' object does not support item assignment
2023-03-20 18:02:55,848 [DEBUG] [OPC-DA] Tentativa -> 2/3
2023-03-20 18:02:55,849 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:02:55,851 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:02:55,880 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:02:55,881 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:02:55,897 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "TypeError("'str' object does not support item assignment",)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[k], group=0)
TypeError: 'str' object does not support item assignment
2023-03-20 18:02:55,900 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x01C51DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 62, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[k], group=0)
TypeError: 'str' object does not support item assignment
2023-03-20 18:05:29,965 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:05:29,966 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:05:29,967 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:05:29,969 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:05:30,196 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:05:30,200 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:05:30,202 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "KeyError('Driver1.Pasta1.Coil',)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil'
2023-03-20 18:05:30,216 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x02091DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil'
2023-03-20 18:05:32,228 [DEBUG] [OPC-DA] Tentativa -> 2/3
2023-03-20 18:05:32,228 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:05:32,230 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:05:32,259 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:05:32,262 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:05:32,264 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "KeyError('Driver1.Pasta1.Coil',)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil'
2023-03-20 18:05:32,265 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x02091DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil'
2023-03-20 18:06:39,021 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:06:39,021 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:06:39,021 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:06:39,023 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:06:39,104 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:06:39,105 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:06:39,105 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "KeyError('Driver1.Pasta1.Coil',)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil'
2023-03-20 18:06:39,109 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x028F1DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil'
2023-03-20 18:06:41,117 [DEBUG] [OPC-DA] Tentativa -> 2/3
2023-03-20 18:06:41,118 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:06:41,121 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:06:41,163 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:06:41,163 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:06:41,164 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "KeyError('Driver1.Pasta1.Coil',)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil'
2023-03-20 18:06:41,166 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x028F1DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil'
2023-03-20 18:13:47,914 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:13:47,921 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:13:47,921 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:13:47,922 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:13:48,065 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:13:48,068 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:13:48,069 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "KeyError('Driver1.Pasta1.Coil.Value',)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil.Value'
2023-03-20 18:13:48,073 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x021C1DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil.Value'
2023-03-20 18:13:50,083 [DEBUG] [OPC-DA] Tentativa -> 2/3
2023-03-20 18:13:50,084 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:13:50,086 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:13:50,114 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:13:50,114 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:13:50,115 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "KeyError('Driver1.Pasta1.Coil.Value',)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil.Value'
2023-03-20 18:13:50,117 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x021C1DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group=0)
KeyError: 'Driver1.Pasta1.Coil.Value'
2023-03-20 18:14:27,357 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:14:27,358 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:14:27,358 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:14:27,359 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:14:27,452 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:14:27,452 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:14:27,453 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "KeyError('Driver1.Pasta1.Coil.Value',)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group='Group0')[0]
KeyError: 'Driver1.Pasta1.Coil.Value'
2023-03-20 18:14:27,457 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x02541DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group='Group0')[0]
KeyError: 'Driver1.Pasta1.Coil.Value'
2023-03-20 18:14:29,472 [DEBUG] [OPC-DA] Tentativa -> 2/3
2023-03-20 18:14:29,473 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:14:29,478 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:14:29,518 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:14:29,520 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:14:29,523 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "KeyError('Driver1.Pasta1.Coil.Value',)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group='Group0')[0]
KeyError: 'Driver1.Pasta1.Coil.Value'
2023-03-20 18:14:29,525 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x02541DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k][0] = self.opc.read(TESTE[r], group='Group0')[0]
KeyError: 'Driver1.Pasta1.Coil.Value'
2023-03-20 18:15:32,170 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:15:32,171 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:15:32,171 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:15:32,172 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:15:32,268 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:15:32,269 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:15:32,280 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "TypeError("'str' object does not support item assignment",)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[k], group='Group0')[0]
TypeError: 'str' object does not support item assignment
2023-03-20 18:15:32,284 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x02A71DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read(TESTE[k], group='Group0')[0]
TypeError: 'str' object does not support item assignment
2023-03-20 18:16:30,786 [INFO ] [OPC-DA] Iniciando tradutor OPC DA.
2023-03-20 18:16:30,787 [DEBUG] [OPC-DA] Tentativa -> 1/3
2023-03-20 18:16:30,787 [INFO ] [OPC-DA] Carregando arquivos de dados ("dados.json").
2023-03-20 18:16:30,790 [INFO ] [OPC-DA] Iniciando servidor de comunicação OPC DA / DNP 3.0
2023-03-20 18:16:30,878 [INFO ] [OPC-DA] Inciando classe de comunicação OPC DA / DNP 3.0
2023-03-20 18:16:30,882 [DEBUG] [OPC-DA] Carregando dados inciais...
2023-03-20 18:16:30,897 [ERROR] [OPC-DA] Houve um erro ao instanciar a classe de comunicação. Exception: "TypeError("'str' object does not support item assignment",)"
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read('Driver1.Pasta1.Coil.Value', group='Group0')[0]
TypeError: 'str' object does not support item assignment
2023-03-20 18:16:30,902 [ERROR] [OPC-DA] Traceback: <function print_stack at 0x027E1DB0>
Traceback (most recent call last):
  File "c:/Users/cog/Desktop/operacao-autonoma/src/conversor/main.py", line 107, in <module>
    com = ConversorOpc(opc, dados)
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 20, in __init__
    self.carregar_dados_iniciais()
  File "c:\Users\cog\Desktop\operacao-autonoma\src\conversor\conversor_dnp.py", line 61, in carregar_dados_iniciais
    self.antigo[k] = self.opc.read('Driver1.Pasta1.Coil.Value', group='Group0')[0]
TypeError: 'str' object does not support item assignment
